### ISSUE TITLE
Crash on worldgen - Appears to be a gregtech block

### ISSUE THREAD

**Issue by Lianite** [Beyond-Reality/BeyondRealityModPack#112]
Pertinent crashlog info:

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 11/8/14 1:44 PM
Description: Exception getting block type in world

java.lang.NullPointerException: Exception getting block type in world
    at net.minecraft.world.World.func_147439_a(World.java:346)
    at gregtech.api.util.GT_Utility.isOpaqueBlock(GT_Utility.java:1031)
    at gregtech.common.blocks.GT_TileEntity_Ores.func_145844_m(GT_TileEntity_Ores.java:71)
    at net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:540)
    at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:276)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.world.World.func_147439_a(World.java:346)

-- Requested block coordinates --
Details:
    Found chunk: true
    Location: World: (-1213,30,-1953), Chunk: (at 3,1,15 in -76,-123; contains blocks -1216,0,-1968 to -1201,255,-1953), Region: (-3,-4; contains chunks -96,-128 to -65,-97, blocks -1536,0,-2048 to -1025,255,-1537)
Stacktrace:
    at net.minecraft.world.World.func_147439_a(World.java:346)
    at gregtech.api.util.GT_Utility.isOpaqueBlock(GT_Utility.java:1031)
    at gregtech.common.blocks.GT_TileEntity_Ores.func_145844_m(GT_TileEntity_Ores.java:71)
    at net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:540)
    at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:276)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
    Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP)
    Entity ID: 873738
    Entity Name: Lianite
    Entity's Exact location: -1140.62, 98.25, -1777.63
    Entity's Block location: World: (-1141,98,-1778), Chunk: (at 11,6,14 in -72,-112; contains blocks -1152,0,-1792 to -1137,255,-1777), Region: (-3,-4; contains chunks -96,-128 to -65,-97, blocks -1536,0,-2048 to -1025,255,-1537)
    Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: world
    All players: 1 total; [GCEntityPlayerMP['Lianite'/873738, l='world', x=-1140.62, y=98.25, z=-1777.63]]
    Chunk stats: ServerChunkCache: 817 Drop: 0
    Level seed: 8827100900895332493
    Level generator: ID 04 - Highlands, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (33,64,-17), Chunk: (at 1,4,15 in 2,-2; contains blocks 32,0,-32 to 47,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 4679409 game time, 4697462 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 88700 (now: false), thunder time: 113381 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Client seemed to do fine, it was the server that crashed, details are from server.

**Comment by alpharulesirulee** [comment]
seems like a problem with gregtech
