### ISSUE TITLE
Crash when opening Industrial Apiary or Scanner

### ISSUE THREAD

**Issue by dakamojo** [Beyond-Reality/BeyondRealityModPack#169]
I'm getting a client crash when opening an Industrial Apiary and the Scanner.  The Apiary was working prior to the 2.2.2B update, but I did not build a Scanner until after the update.

Both have the same crash report.

Description: Rendering screen

java.lang.NoSuchMethodError: net.bdew.gendustry.gui.WidgetPowerCustom.formater()Ljava/text/DecimalFormat;
	at net.bdew.gendustry.gui.WidgetPowerCustom.handleTooltip(WidgetPowerCustom.scala:20)
	at net.bdew.lib.gui.WidgetContainer$$anonfun$handleTooltip$2.apply(WidgetContainer.scala:71)
	at net.bdew.lib.gui.WidgetContainer$$anonfun$handleTooltip$2.apply(WidgetContainer.scala:70)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
	at scala.collection.mutable.MutableList.foreach(MutableList.scala:29)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
	at net.bdew.lib.gui.WidgetContainer$class.handleTooltip(WidgetContainer.scala:70)
	at net.bdew.lib.gui.WidgetContainerWindow.handleTooltip(WidgetContainer.scala:81)
	at net.bdew.lib.gui.BaseScreen.func_73863_a(BaseScreen.scala:55)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1354)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by crawln45** [comment]
This is a known issue. https://github.com/bdew/gendustry/issues/73

**Comment by dakamojo** [comment]
Correct, I forgot to mention that I had researched it and the problem is related to having an incorrect version of BDLib in the pack.

**Comment by Dominance** [comment]
Fixed in next version 2.2.3
