### ISSUE TITLE
Crash when using Osmotic Enchanter

### ISSUE THREAD

**Issue by dakamojo** [Beyond-Reality/BeyondRealityModPack#170]
I get a client and server crash when using an Osmotic Enchanter.  The crash happens when clicking on the button to perform the enchant.  It happens with both a wand and a scepter.  When the server restarts and something causes the chunk to load, the server crashes again.  This occurs in the 2.2.2B update.  The enchanter did work in previous versions.

Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at thaumcraft.common.items.wands.ItemWandCasting.consumeAllVis(ItemWandCasting.java:322)
	at thaumcraft.common.items.wands.ItemWandCasting.consumeAllVisCrafting(ItemWandCasting.java:305)
	at thaumic.tinkerer.common.block.tile.TileEnchanter.func_145845_h(TileEnchanter.java:159)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1995)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Dominance** [comment]
Fixed in next version 2.2.3
