### ISSUE TITLE
Unable to launch beyond reality 2.3.2

### ISSUE THREAD

**Issue by Mackmora** [Beyond-Reality/BeyondRealityModPack#270]
Hello,

Since today when updating to a new version of Beyond Reality, I've encountered a problem.
When installing 2.3.2 fresh, I get the error that the code chicken core Lib file isn't downloaded and get a link via de Jeb installer thingie. So I did that and now this error occurs, (only the last lines from the FML client latest are pasted here.

Any help would be appreciated.

[12:04:21] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_79]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/BlockFire
	at net.minecraft.block.Block.func_149671_p(Block.java:213) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockFire
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
	at net.minecraft.block.Block.func_149671_p(Block.java:213) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: java.lang.RuntimeException: java.io.IOException: The file or directory is corrupted and unreadable
	at codechicken.lib.asm.ASMHelper.dump(ASMHelper.java:164) ~[CodeChickenLib-1.7.10-1.1.3.138-universal.jar:?]
	at codechicken.lib.asm.ASMHelper.dump(ASMHelper.java:169) ~[CodeChickenLib-1.7.10-1.1.3.138-universal.jar:?]
	at codechicken.lib.asm.ASMHelper.dump(ASMHelper.java:173) ~[CodeChickenLib-1.7.10-1.1.3.138-universal.jar:?]
	at codechicken.lib.asm.ModularASMTransformer$ClassNodeTransformerList.transform(ModularASMTransformer.java:42) ~[CodeChickenLib-1.7.10-1.1.3.138-universal.jar:?]
	at codechicken.lib.asm.ModularASMTransformer.transform(ModularASMTransformer.java:283) ~[CodeChickenLib-1.7.10-1.1.3.138-universal.jar:?]
	at codechicken.core.asm.TweakTransformer.transform(TweakTransformer.java:83) ~[CodeChickenCore-1.7.10-1.0.7.46-universal.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
	at net.minecraft.block.Block.func_149671_p(Block.java:213) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: java.io.IOException: The file or directory is corrupted and unreadable
	at java.io.WinNTFileSystem.createFileExclusively(Native Method) ~[?:1.7.0_79]
	at java.io.File.createNewFile(Unknown Source) ~[?:1.7.0_79]
	at codechicken.lib.asm.ASMHelper.dump(ASMHelper.java:155) ~[CodeChickenLib-1.7.10-1.1.3.138-universal.jar:?]
	at codechicken.lib.asm.ASMHelper.dump(ASMHelper.java:169) ~[CodeChickenLib-1.7.10-1.1.3.138-universal.jar:?]
	at codechicken.lib.asm.ASMHelper.dump(ASMHelper.java:173) ~[CodeChickenLib-1.7.10-1.1.3.138-universal.jar:?]
	at codechicken.lib.asm.ModularASMTransformer$ClassNodeTransformerList.transform(ModularASMTransformer.java:42) ~[CodeChickenLib-1.7.10-1.1.3.138-universal.jar:?]
	at codechicken.lib.asm.ModularASMTransformer.transform(ModularASMTransformer.java:283) ~[CodeChickenLib-1.7.10-1.1.3.138-universal.jar:?]
	at codechicken.core.asm.TweakTransformer.transform(TweakTransformer.java:83) ~[CodeChickenCore-1.7.10-1.0.7.46-universal.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
	at net.minecraft.block.Block.func_149671_p(Block.java:213) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more

**Comment by Dominance** [comment]
You are using a newer version of Code Chicken Lib. As far as the download goes. Should be no way possible to install the pack if a download fails. As CodeChicken.Lib is distributed by us which is crossed checked by MD5.
