### ISSUE TITLE
Crash Bug (Thaumic Tinker Tablet)

### ISSUE THREAD

**Issue by spacebuilder2020** [Beyond-Reality/BeyondRealityModPack#408]
The TabletFakePlayer is causing a class cast exception with Forge Essentials and World Edit

java.lang.ClassCastException:` thaumic.tinkerer.common.block.tile.tablet.TabletFakePlayer cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at com.forgeessentials.commands.util.ModuleCommandsEventHandler.playerMoveEvent(ModuleCommandsEventHandler.java:148)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_442_ModuleCommandsEventHandler_playerMoveEvent_PlayerInteractEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100)
	at thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet.startBreaking(TileAnimationTablet.java:232)
	at thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet.swingHit(TileAnimationTablet.java:170)
	at thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet.func_145845_h(TileAnimationTablet.java:114)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at `net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

java.lang.ClassCastException:` thaumic.tinkerer.common.block.tile.tablet.TabletFakePlayer cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at com.sk89q.worldedit.forge.ForgeWorldEdit.onPlayerInteract(ForgeWorldEdit.java:153)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1077_ForgeWorldEdit_onPlayerInteract_PlayerInteractEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100)
	at thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet.startBreaking(TileAnimationTablet.java:232)
	at thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet.swingHit(TileAnimationTablet.java:170)
	at thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet.func_145845_h(TileAnimationTablet.java:114)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at `net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by leagris** [comment]
Should be fixed in-dev with these updates:
* `forgeessentials-1.7.10-1.4.4.1187-server.jar` [:information_source:](http://ci.forgeessentials.com/job/FE/changes)
* `forgeessentials-1.7.10-1.4.4.1187-client.jar` [:information_source:](http://ci.forgeessentials.com/job/FE/changes)
* `worldedit-forge-mc1.7.10-6.1.1-dist.jar` [:information_source:](http://minecraft.curseforge.com/projects/worldedit/files/2309699)
