### ISSUE TITLE
2.4.1-r4 Use flint axe to mine vanilla workbench

### ISSUE THREAD

**Issue by fwsGonzo** [Beyond-Reality/BeyondRealityModPack#437]
Crash
```
java.lang.NullPointerException: Unexpected error
	at gregtech.common.tools.GT_Tool_Axe.isMinableBlock(GT_Tool_Axe.java:83)
	at gregtech.api.items.GT_MetaGenerated_Tool.getDigSpeed(GT_MetaGenerated_Tool.java:438)
	at net.minecraft.entity.player.EntityPlayer.getBreakSpeed(EntityPlayer.java:811)
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:138)
	at net.minecraft.block.Block.func_149737_a(Block.java:643)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78743_b(PlayerControllerMP.java:177)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1409)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1948)
```

**Comment by leagris** [comment]
Fixed in BRC 2.4.2-r1
